import { toPng } from "html-to-image";
import { jsPDF } from "jspdf";

export async function exportToPdf(
  elementId: string,
  filename: string = "fire-report.pdf",
) {
  const element = document.getElementById(elementId);
  if (!element) return;

  // Export honestly in the current theme: a dark-mode page captured on a white
  // background would be "white page + dark text + dark charts". Match the page
  // background and footer color to the active theme instead.
  const isDark = document.documentElement.classList.contains("dark");
  const pageBg = isDark ? "#1a1a1a" : "#ffffff";

  const dataUrl = await toPng(element, {
    pixelRatio: 2,
    backgroundColor: pageBg,
  });

  const img = new Image();
  img.src = dataUrl;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("Failed to load image for PDF export"));
  });

  const pdfWidth = 210;
  const pdfHeight = (img.height * pdfWidth) / img.width;
  const pageHeight = Math.max(pdfHeight + 20, 297);

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: [pdfWidth, pageHeight],
  });

  // Fill the page so top/bottom margins match the captured background.
  pdf.setFillColor(pageBg);
  pdf.rect(0, 0, pdfWidth, pageHeight, "F");

  pdf.addImage(dataUrl, "PNG", 0, 10, pdfWidth, pdfHeight);

  const dateStr = new Date().toISOString().slice(0, 10);
  pdf.setFontSize(8);
  pdf.setTextColor(isDark ? 180 : 150);
  pdf.text(
    `Generated by FIRE Lab | ${dateStr}`,
    pdfWidth / 2,
    pdfHeight + 15,
    { align: "center" },
  );

  pdf.save(filename);
}
