import { toPng } from "html-to-image";
import { jsPDF } from "jspdf";

export async function exportToPdf(
  elementId: string,
  filename: string = "fire-report.pdf",
) {
  const element = document.getElementById(elementId);
  if (!element) return;

  const dataUrl = await toPng(element, {
    pixelRatio: 2,
    backgroundColor: "#ffffff",
  });

  const img = new Image();
  img.src = dataUrl;
  await new Promise<void>((resolve) => { img.onload = () => resolve(); });

  const pdfWidth = 210;
  const pdfHeight = (img.height * pdfWidth) / img.width;

  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: [pdfWidth, Math.max(pdfHeight + 20, 297)],
  });

  pdf.addImage(dataUrl, "PNG", 0, 10, pdfWidth, pdfHeight);

  const dateStr = new Date().toISOString().slice(0, 10);
  pdf.setFontSize(8);
  pdf.setTextColor(150);
  pdf.text(
    `Generated by FIRE Lab | ${dateStr}`,
    pdfWidth / 2,
    pdfHeight + 15,
    { align: "center" },
  );

  pdf.save(filename);
}
